### ISSUE TITLE
Where should I changed the dataset dir?

### ISSUE THREAD

**Issue by WiselyC0430** [zqiuak/De-COMA#1]
Since you do not have any document named DataDict.json, but PathDict.py, should I change the content in it? and how should I devide the data provided?

**Comment by zqiuak** [comment]
Yes, change the PathDict.py to fit your data. We only provide part of the test dataset in the drive. If you want to train your model, you can divide the data in 7:1:2 or run 5-fold validation.

**Comment by wang-qitong** [comment]
> Yes, change the PathDict.py to fit your data. We only provide part of the test dataset in the drive. If you want to train your model, you can divide the data in 7:1:2 or run 5-fold validation.

Hello, how should I reproduce this model using the data you provided ,how should I modify the PathDict.py? Thank you！

<img width="420" alt="Image" src="https://github.com/user-attachments/assets/aa533a35-9b1a-4a8f-a46d-97cfcace7422" />
